global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using OpenIddict.Abstractions;
global using OpenIddict.Server.AspNetCore;
global using PAD.Identity.API.Extensions;
global using PAD.Identity.Core.Services;
global using PAD.Identity.API.Workers;
global using Quartz;
global using System.ComponentModel.DataAnnotations;
global using System.Security.Claims;
global using static OpenIddict.Abstractions.OpenIddictConstants;