version: "3.8"

services:  
  db_finance:
    image: postgres:latest
    ports:
      - "6432:5432"
    restart: always
    environment:
      POSTGRES_DB: "finance"
      POSTGRES_USER: "finance_admin"
      POSTGRES_PASSWORD: "supersecretpassword"